[modules.spotify.token]
access_token = "BQD1fjLfYlJfK2H6OR92dJTxWnXFCiQ6WWriRmHmCQKl4trY7qRsb8hoQOk7e8MtliaN3idoqRRHKBGlqAfT96zgKnwOsMYWEqbBFLP2L6A9MWR1CT5rh2bnVHKs-Frd7ZT84PhxPC_XV6pVZhi08O1IjKDvAtDw1dpeVe-pj8XnYnbEPsElkG9cZMw68KHGTsU76GP3PA"
token_type = "Bearer"
refresh_token = "AQBBy8A-J-kjXWddJrlOyfx-hDBPCTgA65koHOl0Kt-9-Ymk7W48ChyoSZ4fUxEfF7u3uiG5zBy4QHjCWyCfGQEeWJnp-K1zRIh3KzE9rwpHKf97nGugskUvCdfRe8OyxrI"

[modules.spotify.token.expires_in]
secs = 3600
nanos = 0

[modules.spotify.token.time_set]
secs_since_epoch = 1705160464
nanos_since_epoch = 877212000
